version: 2.1
orbs:
  node: circleci/node@1.1.6
  # heroku: circleci/heroku@1.0.1
  # snyk: snyk/snyk@0.0.8
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run:
                name: 'Lint'
                command: yarn run lint
            - run:
                name: 'Build'
                command: yarn run build
            # - snyk/scan
workflows:
  build_deploy:
    jobs:
      - build
      # remove comments to configure deploy via heroku
      # - heroku/deploy-via-git:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
